(function() {var implementors = {};
implementors["enum_primitive"] = ["impl&lt;'a, A, R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a&gt;","impl&lt;'a, A, R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>&gt;","impl&lt;R, F&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() for <a class='struct' href='https://doc.rust-lang.org/nightly/std/panic/struct.AssertUnwindSafe.html' title='std::panic::AssertUnwindSafe'>AssertUnwindSafe</a>&lt;F&gt; <span class='where'>where F: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() -&gt; R</span>",];
implementors["image"] = ["impl&lt;R, F&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() for <a class='struct' href='https://doc.rust-lang.org/nightly/std/panic/struct.AssertUnwindSafe.html' title='std::panic::AssertUnwindSafe'>AssertUnwindSafe</a>&lt;F&gt; <span class='where'>where F: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() -&gt; R</span>","impl&lt;'a, A, R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a&gt;","impl&lt;'a, A, R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>&gt;",];
implementors["libc"] = ["impl&lt;'a, A, R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a&gt;","impl&lt;'a, A, R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>&gt;","impl&lt;R, F&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() for <a class='struct' href='https://doc.rust-lang.org/nightly/std/panic/struct.AssertUnwindSafe.html' title='std::panic::AssertUnwindSafe'>AssertUnwindSafe</a>&lt;F&gt; <span class='where'>where F: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() -&gt; R</span>",];
implementors["num"] = ["impl&lt;'a, A, R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a&gt;","impl&lt;'a, A, R&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='https://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a + <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>&gt;","impl&lt;R, F&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() for <a class='struct' href='https://doc.rust-lang.org/nightly/std/panic/struct.AssertUnwindSafe.html' title='std::panic::AssertUnwindSafe'>AssertUnwindSafe</a>&lt;F&gt; <span class='where'>where F: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>() -&gt; R</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
